# Site settings
title: PCIbex Documentation
description: >- # this means to ignore newlines until "baseurl:"
  PCIbex documentation
baseurl: ""
url: "" 
excerpt_separator: <!--more-->

# Build settings
remote_theme: pmarsceill/just-the-docs
# theme: just-the-docs
logo: "/assets/images/pcibex-logo.png"
# Aux links for the upper right navigation
aux_links:
  "Go to the PCIbex Farm":
    - "https://expt.pcibex.net/"
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
plugins:
  - jekyll-feed
  - jekyll-paginate

# Announcements
paginate: 10
paginate_path: "/announcements/page/:num/"

# Disable Rouge syntax highlighter
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Footer: appears at the bottom of every page's main content
footer_content: "<b>Contact us</b>&#58; <a href=\"mailto&#58; admin@pcibex.net\">admin@pcibex.net</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Collections
collections_dir: reference
collections:
  author:
    output: true
    permalink: /:collection/:name/
  deprecated:
    output: true
    permalink: /:collection/:name/
  elements:
    output: true
    permalink: /:collection/:name/
  global-commands:
    output: true
    permalink: /commands/:collection/:name/
  how-to-guides:
    output: true
    permalink: /docs/:collection/:name/
  posts:
    output: true
    permalink: /announcements/:name/
  special-commands:
    output: true
    permalink: /commands/:collection/:name/
  standard-element-commands:
    output: true
    permalink: /commands/:collection/:name/
  tag:
    output: true
    permalink: /:collection/:name/
  audio:
    output: true
    permalink: /elements/:collection/:name/
  button:
    output: true
    permalink: /elements/:collection/:name/
  canvas:
    output: true
    permalink: /elements/:collection/:name/
  controller:
    output: true
    permalink: /elements/:collection/:name/
  dropdown:
    output: true
    permalink: /elements/:collection/:name/
  eyetracker:
    output: true
    permalink: /elements/:collection/:name/
  function:
    output: true
    permalink: /elements/:collection/:name/
  html:
    output: true
    permalink: /elements/:collection/:name/
  image:
    output: true
    permalink: /elements/:collection/:name/
  key:
    output: true
    permalink: /elements/:collection/:name/
  mediarecorder:
    output: true
    permalink: /elements/:collection/:name/
  mousetracker:
    output: true
    permalink: /elements/:collection/:name/
  scale:
    output: true
    permalink: /elements/:collection/:name/
  selector:
    output: true
    permalink: /elements/:collection/:name/
  text:
    output: true
    permalink: /elements/:collection/:name/
  textinput:
    output: true
    permalink: /elements/:collection/:name/
  timer:
    output: true
    permalink: /elements/:collection/:name/
  tooltip:
    output: true
    permalink: /elements/:collection/:name/
  var:
    output: true
    permalink: /elements/:collection/:name/
  video:
    output: true
    permalink: /elements/:collection/:name/           
  youtube:
    output: true
    permalink: /elements/:collection/:name/

# Front matter defaults
defaults:
  - scope:
      path: "advanced-tutorial"
    values:
      layout: "bottom-navbar-child"
      parent: "Advanced Tutorial"
      numbered_headings: true
  - scope:
      path: "basic-tutorial"
    values:
      layout: "bottom-navbar-child"
      parent: "Basic Tutorial"
      numbered_headings: true
  - scope:
      path: "core-concepts"
    values:
      layout: "bottom-navbar-child"
      parent: "Core Concepts"
      numbered_headings: true
  - scope:
      path: "deprecated"
    values:
      layout: "default"
      parent: "⚠ Deprecated features"
      exclude_permalink: true
      has_children: true
      has_toc: false
      children_collection: deprecated
      children_code_font: true
  - scope:
      path: "reference/_author"
    values:
      layout: "tag"
      nav_exclude: true
      tag: false
  - scope:
      path: "reference/_elements"
    values:
      layout: "element"
      parent: "Elements"
      has_children: true
      has_toc: false
      children_code_font: true
  - scope:
      path: "reference/_deprecated"
    values:
      layout: "command"
      grand_parent: "⚠ Deprecated features"    
  - scope:
      path: "reference/_how-to-guides"
    values:
      layout: "how-to-guide"
      parent: "How-to guides"
  - scope:
      path: "reference/_global-commands"
    values:
      layout: "command"
      command_type: "global"
      parent: "Global commands"
      grand_parent: "Commands"
  - scope:
      path: "reference/_posts"
    values:
      layout: "post"
  - scope:
      path: "reference/_special-commands"
    values:
      layout: "command"
      command_type: "special"
      parent: "Special commands"
      grand_parent: "Commands"
  - scope:
      path: "reference/_standard-element-commands"
    values:
      layout: "command"
      parent: "Standard element commands"
      grand_parent: "Commands"
  - scope:
      path: "reference/_tag"
    values:
      layout: "tag"
      nav_exclude: true
  - scope:
      path: "reference/_audio"
    values:
      layout: "command"
      element_type: "audio"
      parent: "Audio"
      grand_parent: "Elements"
  - scope:
      path: "reference/_button"
    values:
      layout: "command"
      element_type: "button"
      parent: "Button"
      grand_parent: "Elements"
  - scope:
      path: "reference/_canvas"
    values:
      layout: "command"
      element_type: "canvas"
      parent: "Canvas"
      grand_parent: "Elements"
  - scope:
      path: "reference/_controller"
    values:
      layout: "command"
      element_type: "controller"
      parent: "Controller"
      grand_parent: "Elements"
  - scope:
      path: "reference/_dropdown"
    values:
      layout: "command"
      element_type: "dropdown"
      parent: "DropDown"
      grand_parent: "Elements"
  - scope:
      path: "reference/_eyetracker"
    values:
      layout: "command"
      element_type: "eyetracker"
      parent: "EyeTracker"
      grand_parent: "Elements"
  - scope:
      path: "reference/_function"
    values:
      layout: "command"
      element_type: "function"
      parent: "Function"
      grand_parent: "Elements"
  - scope:
      path: "reference/_html"
    values:
      layout: "command"
      element_type: "html"
      parent: "Html"
      grand_parent: "Elements"
  - scope:
      path: "reference/_image"
    values:
      layout: "command"
      element_type: "image"
      parent: "Image"
      grand_parent: "Elements"
  - scope:
      path: "reference/_key"
    values:
      layout: "command"
      element_type: "key"
      parent: "Key"
      grand_parent: "Elements"
  - scope:
      path: "reference/_mediarecorder"
    values:
      layout: "command"
      element_type: "mediarecorder"
      parent: "MediaRecorder"
      grand_parent: "Elements"
  - scope:
      path: "reference/_mousetracker"
    values:
      layout: "command"
      element_type: "mousetracker"
      parent: "MouseTracker"
      grand_parent: "Elements"
  - scope:
      path: "reference/_scale"
    values:
      layout: "command"
      element_type: "scale"
      parent: "Scale"
      grand_parent: "Elements"
  - scope:
      path: "reference/_selector"
    values:
      layout: "command"
      element_type: "selector"
      parent: "Selector"
      grand_parent: "Elements"
  - scope:
      path: "reference/_text"
    values:
      layout: "command"
      element_type: "text"
      parent: "Text"
      grand_parent: "Elements"
  - scope:
      path: "reference/_textinput"
    values:
      layout: "command"
      element_type: "textinput"
      parent: "TextInput"
      grand_parent: "Elements"
  - scope:
      path: "reference/_timer"
    values:
      layout: "command"
      element_type: "timer"
      parent: "Timer"
      grand_parent: "Elements"
  - scope:
      path: "reference/_tooltip"
    values:
      layout: "command"
      element_type: "tooltip"
      parent: "Tooltip"
      grand_parent: "Elements"
  - scope:
      path: "reference/_var"
    values:
      layout: "command"
      element_type: "var"
      parent: "Var"
      grand_parent: "Elements"
  - scope:
      path: "reference/_video"
    values:
      layout: "command"
      element_type: "video"
      parent: "Video"
      grand_parent: "Elements"
  - scope:
      path: "reference/_youtube"
    values:
      layout: "command"
      element_type: "youtube"
      parent: "Youtube"
      grand_parent: "Elements"
      
# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
